project 'BradleyUTour.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'BradleyUTour' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RealmSwift'
  
end
